### ISSUE TITLE
The "iconic" theme creates a black bar across the top of the page that interferes with the page heading

### ISSUE THREAD

**Issue by faunaee** [DocOps/asciidocsy-jekyll-theme#13]
<img width="1233" alt="iconic-theme" src="https://user-images.githubusercontent.com/46354154/119176120-8d29a000-ba1f-11eb-9b40-ae580e8910ee.png">

**Comment by briandominick** [comment]
Ah, yikes. Good catch! Might be a simple CSS fix, otherwise I might just drop that skin from the list.

**Comment by briandominick** [comment]
So I fired up Inspector and could not even highlight the problem area. I really like the idea of all the skins working, but really the differences are so slight, and this one is barely discernible from others... still, I'm going to hang up a Help wanted flag, since it's early days and maybe somebody will just know what's causing this or have a better inspector.

**Comment by faunaee** [comment]
Since you have removed the "iconic" theme, this issue is moot.
