### ISSUE TITLE
Table of content path: manifest.yml?

### ISSUE THREAD

**Issue by gbv34** [DocOps/asciidocsy-jekyll-theme#72]
Hello,
I apologize in advance because this ticket isn't related to an issue, but rather a question about the usage of the theme. I got acquainted with Jekyll and "Documentation Theme" developed by Tom Johnson. But I wanted to make it compliant with AsciiDoc instead of Markdown, that's how I discovered and installed this project, which is amazing, btw!

I'm currently trying to understand the structure and how items are organized and regarding the TOC, I've found that it is available under "manifest.yml". However, what if I want to target another file as a TOC? My point is to keep the actual file as a backup and replace it with another file, for instance "my-new-toc.yml". I think it might be easier to target the TOC that will be displayed in the "Subject nav". I haven't found it in the main config file.

What am I missing?
Thanks for your feedback!

**Comment by briandominick** [comment]
@gbv34 This is a fine issue. I'm glad you asked.

When I release 0.3.0, the theme will be a gem, which means the core datafiles will be in the gem, and you can override any given file just by creating an alternate in your local workspace. So then you'll be able to just create your own manifest file, no renaming needed.

For now, I would advise one of two things, in this order of preference.

1. Rename the existing file `manifest.yml.bak` or something else just to get it out of the way, and then reproduce your own manifest as `manifest.yml`.
2. Replace any reference to the data object `site.manifest` with `site.my-new-toc.yml`.

Also technically the TOC is the right-hand menu that shows the current topic TOC. I call the left menu the "Subject menu" because it covers the broad subject/product. You can call them whatever you want but I'm trying to stay consistent in the docs so as not to cause confusion.

Good luck and I'm super happy to answer other stuff like this as you come across it. Don't worry about having too many questions.

**Comment by gbv34** [comment]
Hi Brian,

Thank you so much for clarifying my question and helping me to move forward!Now 
Now, I understand that the "Subject menu" includes all the topics related to a product. While the TOC visible in the right menu allows navigating inside the topic, based on its headings.

However, suppose I have about 30 different products that need a doc for each one. I mistakenly thought that if I had a different manifest.yaml file for each of my products, the generation would only concern the pages referenced in this manifest. However, it appears that all the contents placed in my _docs folder, even if they are divided into subfolders, will be generated and then placed in the _site folder.

How could I generate only one single documentation which refers to a specific manifest file? Or does the solution consist to use permalinks to split each product into a corresponding subfolder?
Example:

_site/product1/
...
...
_site/product9/

Thanks again for your support!

**Comment by briandominick** [comment]
Another good question. You mentioned Tom Johnson's theme before, and I also used that extensively (I think I built sites for 6 different companies with it), and I carried most of the logic forward.

With Jekyll, you're getting site structure for a big docset one of two ways: permalinks or multiple builds. When I build mutli-product sites, I perform a distinct build for each product (or each version of each product, but let's keep it simple for now). I have a common Jekyll config, and I have a config for each product, which might contain `destination: _site/product1` and so forth. Then I perform the builds sequentially, building a distinct "site" into parallel suibdirectories like that.

As for building all your docs when you only want some, that becomes a problem with this method, inherent to Jekyll, which will try to build all qualifying files in your source directory, recursively. To handle this, add the `exclude` object to the product-specific Jekyll config, then it will exclude all the source directories that you are not building at the moment.

Before I go any further, I should explain that normally I handle all of this with external tooling -- it's really not about the theme so much as it is about getting the right data and the right sources into the right builds and out to the right destinations. Since I do this by "tricking" Jekyll and building a bunch of sites next to each other under `_site/`, most of the work is done outside Jekyll with a tool called [LiquiDoc](https://github.com/DocOps/liquidoc-gem). I also have an open-source framework for this, and I'm rushing to get it and LiquiDoc into shape this fall so I can demonstrate how it's all used together.

Back to Jekyll/AsciiDocsy: The big advantage to building multiple parallel sites is that each one can have its own data/variables that only apply to that product, so you can single source more easily. The product name itself and other key characteristics/metadata can be a variables in common topics, etc.

None of my clients have open sourced their docs, so I still have not put out a full set of docs that uses this system. It is the basis for this repo that is in kind of bad shape, but all the logic is there. https://github.com/DocOps/liquidoc-cmf-guides. The [build script](https://github.com/DocOps/liquidoc-cmf-guides/blob/master/_configs/build-docs.yml) might give you some clues, and also note the [individual Jekyll configs](https://github.com/DocOps/liquidoc-cmf-guides/blob/master/_configs/jekyll-guide-dev.yml) for the different role-based guides (which are the subjects of that particular repo, rather than products being the subjects).

So much more coming over the rest of the year, and I'm happy to keep answering questions. Also open to suggestions!

**Comment by gbv34** [comment]
Thanks a lot for all this information, Brian. That makes sense and it's pretty useful!
